/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ismt.assignment2;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author rajeshadhikari
 */
public class BookingScreen extends javax.swing.JFrame {

    String carTypes[] = {"Please Select","City Car", "Family Car (+$50)", "Sports Car (+$75)", "SUV (+$65)"};
    String fuleTypes[] = {"Please Select","Petrol", "Diesel", "Hybrid (+$30)", "Full Electric (+$50)"};

    /**
     * Creates new form BookingScreen
     */
    public BookingScreen() {
        initComponents();
        buttonGroup1.add(rb_valid_license);
        buttonGroup1.add(rb_invalid_license);
        cb_car_type.removeAllItems();
        cb_fule_type.removeAllItems();

        for (String e : carTypes) {
            cb_car_type.addItem(e);

        }
        for (String e1 : fuleTypes) {
            cb_fule_type.addItem(e1);

        }

        URL imageUrl = getClass().getResource("/images/icon1.png");
        if (imageUrl == null) {
            System.out.println("Image not found!");
        } else {
            jLabel1.setIcon(new ImageIcon(new ImageIcon(imageUrl).getImage().getScaledInstance(40, 40, Image.SCALE_DEFAULT)));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_surname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_address = new javax.swing.JTextField();
        tf_age = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rb_valid_license = new javax.swing.JRadioButton();
        rb_invalid_license = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        cb_car_type = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cb_fule_type = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        check_milage = new javax.swing.JCheckBox();
        check_coverage = new javax.swing.JCheckBox();
        bt_book_car = new javax.swing.JButton();
        tf_no_of_days = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("WeAreCars");

        jLabel2.setText("Welcome: ");

        jLabel3.setText("Date: ");

        jLabel4.setText("First Name:*");

        tf_name.setToolTipText("First Name");
        tf_name.setMinimumSize(new java.awt.Dimension(64, 32));
        tf_name.setPreferredSize(new java.awt.Dimension(78, 42));

        jLabel5.setText("Surname:*");

        tf_surname.setToolTipText("Surname");
        tf_surname.setPreferredSize(new java.awt.Dimension(78, 42));

        jLabel6.setText("Address:*");

        tf_address.setToolTipText("Address");
        tf_address.setPreferredSize(new java.awt.Dimension(78, 42));

        tf_age.setToolTipText("Age");
        tf_age.setPreferredSize(new java.awt.Dimension(78, 42));
        tf_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_ageKeyPressed(evt);
            }
        });

        jLabel7.setText("Age:*");

        rb_valid_license.setText("Yes");
        rb_valid_license.setPreferredSize(new java.awt.Dimension(45, 32));

        rb_invalid_license.setText("No");
        rb_invalid_license.setPreferredSize(new java.awt.Dimension(39, 32));

        jLabel8.setText("Valid License:*");
        jLabel8.setPreferredSize(new java.awt.Dimension(87, 42));

        cb_car_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_car_type.setMinimumSize(new java.awt.Dimension(72, 30));
        cb_car_type.setPreferredSize(new java.awt.Dimension(72, 42));

        jLabel9.setText("Type Of Car:*");

        cb_fule_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_fule_type.setMinimumSize(new java.awt.Dimension(72, 30));
        cb_fule_type.setPreferredSize(new java.awt.Dimension(72, 42));

        jLabel10.setText("Type Of Fule:*");

        check_milage.setText("Unlimited Milage ( +$10)");
        check_milage.setPreferredSize(new java.awt.Dimension(93, 32));

        check_coverage.setText("Breakdown Cover ( +$2)");
        check_coverage.setPreferredSize(new java.awt.Dimension(93, 42));

        bt_book_car.setText("Book Now");
        bt_book_car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_book_carActionPerformed(evt);
            }
        });

        tf_no_of_days.setToolTipText("Number Of Days");
        tf_no_of_days.setPreferredSize(new java.awt.Dimension(78, 42));
        tf_no_of_days.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_no_of_daysKeyPressed(evt);
            }
        });

        jLabel11.setText("Number Of Days:*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_address, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(55, 55, 55)
                            .addComponent(tf_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(22, 22, 22)
                            .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rb_valid_license, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rb_invalid_license, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tf_age, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_no_of_days, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_car_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_fule_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(check_milage, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_coverage, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_book_car, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_valid_license, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_invalid_license, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_no_of_days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_car_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_fule_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_milage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_coverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(bt_book_car, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Booking", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Surname", "Address", "Age", "Valid License", "Number of Day's", "Car Type", "Fule Type", "Unlimited Milage", "Breakdown Cover", "Net Amount", "Date Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("View Booking", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(22, 22, 22))
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_ageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_ageKeyPressed
        // TODO add your handling code here:
        String age = tf_age.getText();
        int length = age.length();
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= "0".charAt(0) && evt.getKeyChar() <= "9".charAt(0)) {
            if (length < 2) {
                tf_age.setEditable(true);
            } else {
                tf_age.setEditable(false);

            }
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                tf_age.setEditable(true);

            } else {
                tf_age.setEditable(false);

            }
        }
    }//GEN-LAST:event_tf_ageKeyPressed

    private void tf_no_of_daysKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_no_of_daysKeyPressed
        String age = tf_no_of_days.getText();
        int length = age.length();
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= "0".charAt(0) && evt.getKeyChar() <= "9".charAt(0)) {
            if (length < 2) {
                tf_no_of_days.setEditable(true);
            } else {
                tf_no_of_days.setEditable(false);

            }
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                tf_no_of_days.setEditable(true);

            } else {
                tf_no_of_days.setEditable(false);

            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tf_no_of_daysKeyPressed

    private void bt_book_carActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_book_carActionPerformed
        // TODO add your handling code here:
        if (tf_name.getText().isBlank() || tf_name.getText().isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "First name is required");
            return;
        }
         if (tf_name.getText().length()<3) {
            JOptionPane.showMessageDialog(rootPane, "First name is too short");
            return;
        }
        if (tf_surname.getText().isBlank() || tf_surname.getText().isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Surname is required");
            return;
        }
        if (tf_surname.getText().length() < 3) {
            JOptionPane.showMessageDialog(rootPane, "Surname is too short");
            return;
        }
        if (tf_address.getText().isBlank() || tf_address.getText().isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Address is required");
            return;
        }
        if (tf_address.getText().length() < 3) {
            JOptionPane.showMessageDialog(rootPane, "Address is too short");
            return;
        }
        if (tf_age.getText().isBlank() || tf_age.getText().isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Address is required");
            return;
        }
        if (Integer.parseInt(tf_age.getText()) < 16) {
            JOptionPane.showMessageDialog(rootPane, "Age should be 16+ to rent car");
            return;
        }
        if (!rb_valid_license.isSelected() || rb_invalid_license.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "Sorry!! License is invalid can't rent a car");
            return;
        }
        if (cb_car_type.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(rootPane, "Please select car type");
            return;
        }
        if (cb_fule_type.getSelectedIndex()==0) {
            JOptionPane.showMessageDialog(rootPane, "Please select fule type");
            return;
        }
        if(tf_no_of_days.getText().isBlank() ||tf_no_of_days.getText().isBlank()){
            JOptionPane.showMessageDialog(rootPane, "No of day's is required");
            return;
        }
        if(Integer.parseInt(tf_no_of_days.getText()) < 1 ||Integer.parseInt(tf_no_of_days.getText()) > 28){
            JOptionPane.showMessageDialog(rootPane, "No of day's should be from 1 to 28");
            return;
        }
            System.out.println("Add Date");
    }//GEN-LAST:event_bt_book_carActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_book_car;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_car_type;
    private javax.swing.JComboBox<String> cb_fule_type;
    private javax.swing.JCheckBox check_coverage;
    private javax.swing.JCheckBox check_milage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rb_invalid_license;
    private javax.swing.JRadioButton rb_valid_license;
    private javax.swing.JTextField tf_address;
    private javax.swing.JTextField tf_age;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_no_of_days;
    private javax.swing.JTextField tf_surname;
    // End of variables declaration//GEN-END:variables
}
